//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WiZaRo.CommandLine.Support {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WiZaRo.CommandLine.Support.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection does not contain any alias. At least one alias must be defined..
        /// </summary>
        internal static string ErrorAliasesCollectionEmpty {
            get {
                return ResourceManager.GetString("ErrorAliasesCollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one alias must be defined..
        /// </summary>
        internal static string ErrorAliasesCollectionLastRemoved {
            get {
                return ResourceManager.GetString("ErrorAliasesCollectionLastRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases must not be null or contain whitespaces..
        /// </summary>
        internal static string ErrorAliasInvalid {
            get {
                return ResourceManager.GetString("ErrorAliasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of an argument cannot be null or made of only whitespaces..
        /// </summary>
        internal static string ErrorArgumentNameInvalid {
            get {
                return ResourceManager.GetString("ErrorArgumentNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add root command builders to the collection..
        /// </summary>
        internal static string ErrorBuilderIsRoot {
            get {
                return ResourceManager.GetString("ErrorBuilderIsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate created a root command when a non-root command was needed..
        /// </summary>
        internal static string ErrorBuiltRootCommand {
            get {
                return ResourceManager.GetString("ErrorBuiltRootCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An alias in the collection is invalid. Aliases must not be null or contain whitespaces..
        /// </summary>
        internal static string ErrorCollectionContainsInvalidAlias {
            get {
                return ResourceManager.GetString("ErrorCollectionContainsInvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command must be a non-root command..
        /// </summary>
        internal static string ErrorCommandIsRoot {
            get {
                return ResourceManager.GetString("ErrorCommandIsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a command cannot be null or contain whitespaces..
        /// </summary>
        internal static string ErrorCommandNameInvalid {
            get {
                return ResourceManager.GetString("ErrorCommandNameInvalid", resourceCulture);
            }
        }
    }
}
